// In-memory mock database for ARD Ziguinchor portal
// Generated from official seed data to allow full functionality offline or without external database

export const mockParametresSite = {
  id: 'param-1',
  nomSite: 'ARD Ziguinchor',
  description: 'Agence Régionale de Développement de Ziguinchor – Au service du développement local',
  adresse: 'Boulevard des 54m, BP 321, Ziguinchor, Sénégal',
  telephone: '+221 33 991 12 34',
  email: 'contact@ard-ziguinchor.sn',
  ville: 'Ziguinchor',
  facebook: 'https://facebook.com/ardziguinchor',
  twitter: 'https://twitter.com/ardziguinchor',
  linkedin: 'https://linkedin.com/company/ardziguinchor',
  youtube: 'https://youtube.com/@ardziguinchor',
  logo: '/logo_ardz.png',
};

export const mockChiffresCles = [
  { id: '1', label: 'Départements', valeur: '3', description: 'Ziguinchor, Bignona, Oussouye', icone: '🏛️' },
  { id: '2', label: 'Communes', valeur: '30', description: 'Collectivités territoriales accompagnées', icone: '🗺️' },
  { id: '3', label: 'Population', valeur: '617 567', description: 'Estimation ANSD 2023', icone: '👥' },
  { id: '4', label: 'Superficie', valeur: '7 329 km²', description: 'Région de Ziguinchor', icone: '📍' },
  { id: '5', label: 'Vallées réhabilitées', valeur: '3 300 ha', description: 'Programme PDEC', icone: '🌾' },
  { id: '6', label: 'Programmes actifs', valeur: '6', description: 'Appui au développement local', icone: '🚀' },
];

export const mockBannieres = [
  {
    id: '1',
    titre: 'Au service du développement de la région',
    sousTitre: "L'Agence Régionale de Développement de Ziguinchor accompagne les collectivités locales, mobilise les financements et pilote les projets de développement territorial.",
    image: '/img_banniere.jpg',
    lien: '/projets',
    actif: true,
    ordre: 1,
  },
];

export const mockSecteurs = [
  { id: 'sec-agri', nom: 'Agriculture', slug: 'agriculture', description: 'Secteur agricole et développement rural', icone: 'Wheat', couleur: '#16A34A' },
  { id: 'sec-infra', nom: 'Infrastructures', slug: 'infrastructures', description: 'Infrastructures et équipements de base', icone: 'Building2', couleur: '#0284C7' },
  { id: 'sec-edu', nom: 'Éducation', slug: 'education', description: "Secteur de l'éducation et formation professionnelle", icone: 'GraduationCap', couleur: '#EA580C' },
  { id: 'sec-sante', nom: 'Santé', slug: 'sante', description: 'Secteur de la santé communautaire', icone: 'HeartPulse', couleur: '#DC2626' },
  { id: 'sec-env', nom: 'Environnement', slug: 'environnement', description: 'Environnement, climat et biodiversité', icone: 'Trees', couleur: '#059669' },
  { id: 'sec-eco', nom: 'Économie', slug: 'economie', description: 'Développement économique et entrepreneuriat', icone: 'Briefcase', couleur: '#7C3AED' },
  { id: 'sec-gouv', nom: 'Gouvernance', slug: 'gouvernance', description: 'Gouvernance locale, décentralisation et renforcement des capacités', icone: 'Landmark', couleur: '#334155' },
  { id: 'sec-tourisme', nom: 'Tourisme', slug: 'tourisme', description: 'Tourisme, écotourisme et patrimoine', icone: 'Palmtree', couleur: '#0D9488' },
  { id: 'sec-eau', nom: 'Eau et Assainissement', slug: 'eau-assainissement', description: 'Accès à l’eau potable, hydraulique et assainissement', icone: 'Droplets', couleur: '#2563EB' },
  { id: 'sec-transport', nom: 'Transport et Mobilité', slug: 'transport-mobilite', description: 'Pistes, routes, transport et mobilité régionale', icone: 'Bus', couleur: '#B45309' },
  { id: 'sec-elevage', nom: 'Élevage', slug: 'elevage', description: 'Élevage et filières pastorales', icone: 'Beef', couleur: '#92400E' },
  { id: 'sec-peche', nom: 'Pêche', slug: 'peche', description: 'Pêche artisanale et économie maritime', icone: 'Fish', couleur: '#0891B2' },
  { id: 'sec-energie', nom: 'Énergie', slug: 'energie', description: 'Énergie et électrification', icone: 'Zap', couleur: '#CA8A04' },
  { id: 'sec-jeunesse', nom: 'Jeunesse et Insertion professionnelle', slug: 'jeunesse-insertion', description: 'Insertion professionnelle des jeunes et des femmes', icone: 'Users', couleur: '#7C2D12' },
  { id: 'sec-culture', nom: 'Culture et Patrimoine', slug: 'culture-patrimoine', description: 'Culture, patrimoine et cohésion sociale', icone: 'Theater', couleur: '#9333EA' },
  { id: 'sec-urbanisme', nom: 'Urbanisme et Aménagement', slug: 'urbanisme-amenagement', description: 'Urbanisme, aménagement du territoire et foncier', icone: 'MapPinned', couleur: '#475569' },
];

export const mockCategoriesActualite = [
  { id: 'cat-actu', nom: 'Actualité', slug: 'actualite', description: 'Actualités générales' },
  { id: 'cat-comm', nom: 'Communiqué', slug: 'communique', description: 'Communiqués officiels' },
  { id: 'cat-event', nom: 'Événement', slug: 'evenement', description: 'Événements et rencontres' },
];

export const mockCategoriesDocument = [
  { id: 'cat-rap', nom: 'Rapport', slug: 'rapport', description: "Rapports d'activité" },
  { id: 'cat-etu', nom: 'Étude', slug: 'etude', description: 'Études et diagnostics territoriaux' },
  { id: 'cat-pla', nom: 'Plan', slug: 'plan', description: 'Plans de développement (PDC, PRDI)' },
  { id: 'cat-gui', nom: 'Guide', slug: 'guide', description: 'Guides méthodologiques' },
];

export const mockTypesOpportunite = [
  { id: 'typ-app-offres', nom: "Appel d'offres" },
  { id: 'typ-app-projets', nom: 'Appel à projets' },
  { id: 'typ-recrutement', nom: 'Recrutement' },
  { id: 'typ-stage', nom: 'Stage' },
  { id: 'typ-formation', nom: 'Formation' },
];

export const mockTypesPartenaires = [
  { id: 'typ-ptf', nom: 'PTF', description: 'Partenaire technique et financier' },
  { id: 'typ-ong', nom: 'ONG', description: 'Organisation non gouvernementale' },
  { id: 'typ-inst', nom: 'Institutionnel', description: 'Partenaire institutionnel' },
  { id: 'typ-priv', nom: 'Privé', description: 'Partenaire privé' },
];

export const mockDepartements = [
  {
    id: 'dept-zg',
    nom: 'Ziguinchor',
    code: 'ZG',
    superficie: 1153,
    population: 275501,
    description: "Chef-lieu régional et capitale historique de la Basse-Casamance, le département de Ziguinchor constitue le principal pôle administratif, économique et universitaire de la région.",
  },
  {
    id: 'dept-bn',
    nom: 'Bignona',
    code: 'BN',
    superficie: 5295,
    population: 287499,
    description: "Plus grand département de la région par sa superficie et sa population, Bignona est le poumon agricole et forestier de la Basse-Casamance.",
  },
  {
    id: 'dept-oy',
    nom: 'Oussouye',
    code: 'OY',
    superficie: 891,
    population: 54567,
    description: "Cœur historique du royaume diola du Kasa, le département d'Oussouye se distingue par ses traditions vivaces, sa biodiversité exceptionnelle et son attractivité touristique (Cap Skirring).",
  },
];

export const mockArrondissements = [
  { id: 'arr-zg-niaguis', nom: 'Niaguis', code: 'ZG-NIAGUIS', departementId: 'dept-zg', departement: mockDepartements[0] },
  { id: 'arr-zg-niassia', nom: 'Niassia', code: 'ZG-NIASSIA', departementId: 'dept-zg', departement: mockDepartements[0] },
  { id: 'arr-bn-kataba1', nom: 'Kataba 1', code: 'BN-KATABA1', departementId: 'dept-bn', departement: mockDepartements[1] },
  { id: 'arr-bn-tenghory', nom: 'Tenghory', code: 'BN-TENGHORY', departementId: 'dept-bn', departement: mockDepartements[1] },
  { id: 'arr-bn-tendouck', nom: 'Tendouck', code: 'BN-TENDOUCK', departementId: 'dept-bn', departement: mockDepartements[1] },
  { id: 'arr-bn-sindian', nom: 'Sindian', code: 'BN-SINDIAN', departementId: 'dept-bn', departement: mockDepartements[1] },
  { id: 'arr-oy-cabrousse', nom: 'Cabrousse', code: 'OY-CABROUSSE', departementId: 'dept-oy', departement: mockDepartements[2] },
  { id: 'arr-oy-loudia', nom: 'Loudia Ouoloff', code: 'OY-LOUDIA', departementId: 'dept-oy', departement: mockDepartements[2] },
];

export const mockCommunes = [
  { id: 'com-zg', nom: 'Ziguinchor', code: 'ZG-COM-ZG', departementId: 'dept-zg', departement: mockDepartements[0], arrondissementId: undefined, superficie: 156.8, population: 214874, latitude: 12.5833, longitude: -16.2719, description: "Capitale régionale de la Basse-Casamance, important centre économique, portuaire et universitaire." },
  { id: 'com-adeane', nom: 'Adéane', code: 'ZG-COM-ADEANE', departementId: 'dept-zg', departement: mockDepartements[0], arrondissementId: 'arr-zg-niaguis', superficie: 182.4, population: 19728, latitude: 12.63, longitude: -16.02, description: "Commune agricole réputée pour ses vergers d'agrumes et ses rizières." },
  { id: 'com-boutoupa', nom: 'Boutoupa-Camaracounda', code: 'ZG-COM-BOUTOUPA', departementId: 'dept-zg', departement: mockDepartements[0], arrondissementId: 'arr-zg-niaguis', superficie: 154.7, population: 8682, latitude: 12.52, longitude: -16.08, description: "Vastes terroirs agricoles et patrimoine culturel diola." },
  { id: 'com-enampore', nom: 'Enampore', code: 'ZG-COM-ENAMPORE', departementId: 'dept-zg', departement: mockDepartements[0], arrondissementId: 'arr-zg-niassia', superficie: 78.3, population: 4877, latitude: 12.51, longitude: -16.45, description: "Célèbre pour ses cases à impluvium et son écotourisme intégré." },
  { id: 'com-niaguis', nom: 'Niaguis', code: 'ZG-COM-NIAGUIS', departementId: 'dept-zg', departement: mockDepartements[0], arrondissementId: 'arr-zg-niaguis', superficie: 98.5, population: 21671, latitude: 12.56, longitude: -16.19, description: "Commune fluviale bordant la rive gauche du fleuve Casamance." },
  { id: 'com-niassia', nom: 'Niassia', code: 'ZG-COM-NIASSIA', departementId: 'dept-zg', departement: mockDepartements[0], arrondissementId: 'arr-zg-niassia', superficie: 112.6, population: 5669, latitude: 12.49, longitude: -16.35, description: "Zone forestière et rizicole au sud de Ziguinchor." },
  { id: 'com-bignona', nom: 'Bignona', code: 'BN-COM-BIGNONA', departementId: 'dept-bn', departement: mockDepartements[1], arrondissementId: undefined, superficie: 213.2, population: 28642, latitude: 12.81, longitude: -16.23, description: "Deuxième ville de la région, carrefour commercial stratégique vers la Gambie." },
  { id: 'com-kafountine', nom: 'Kafountine', code: 'BN-COM-KAFOUNTINE', departementId: 'dept-bn', departement: mockDepartements[1], arrondissementId: 'arr-bn-kataba1', superficie: 198.5, population: 41590, latitude: 12.93, longitude: -16.75, description: "Grand port de pêche artisanale et station touristique atlantique." },
  { id: 'com-thionck', nom: 'Thionck-Essyl', code: 'BN-COM-THIONCK', departementId: 'dept-bn', departement: mockDepartements[1], arrondissementId: 'arr-bn-tendouck', superficie: 182.7, population: 8961, latitude: 12.79, longitude: -16.51, description: "Cité historique du Blouf réputée pour ses bois sacrés et son dynamisme communautaire." },
  { id: 'com-diouloulou', nom: 'Diouloulou', code: 'BN-COM-DIOULOULOU', departementId: 'dept-bn', departement: mockDepartements[1], arrondissementId: 'arr-bn-kataba1', superficie: 187.6, population: 8109, latitude: 13.04, longitude: -16.65, description: "Carrefour frontalier avec la Gambie, centre commercial et de production de sel." },
  { id: 'com-tenghory', nom: 'Tenghory', code: 'BN-COM-TENGHORY', departementId: 'dept-bn', departement: mockDepartements[1], arrondissementId: 'arr-bn-tenghory', superficie: 172.3, population: 39509, latitude: 12.84, longitude: -16.22, description: "Bassin de production agricole entourant la commune urbaine de Bignona." },
  { id: 'com-oussouye', nom: 'Oussouye', code: 'OY-COM-OUSSOUYE', departementId: 'dept-oy', departement: mockDepartements[2], arrondissementId: undefined, superficie: 145.6, population: 5705, latitude: 12.48, longitude: -16.55, description: "Chef-lieu du département et siège de la royauté traditionnelle diola (Maan)." },
  { id: 'com-diembering', nom: 'Diembéring', code: 'OY-COM-DIEMBERING', departementId: 'dept-oy', departement: mockDepartements[2], arrondissementId: 'arr-oy-cabrousse', superficie: 98.3, population: 25902, latitude: 12.42, longitude: -16.78, description: "Englobe la station balnéaire internationale de Cap Skirring et de magnifiques plages." },
  { id: 'com-mlomp-oy', nom: 'Mlomp (Oussouye)', code: 'OY-COM-MLOMP', departementId: 'dept-oy', departement: mockDepartements[2], arrondissementId: 'arr-oy-cabrousse', superficie: 72.5, population: 11426, latitude: 12.55, longitude: -16.58, description: "Célèbre pour ses fromagers géants et ses maisons traditionnelles à étages en terre cuite." },
];

export const mockProgrammes = [
  {
    id: 'prog-pdec',
    nom: 'Projet de Développement Économique de la Casamance',
    acronyme: 'PDEC',
    slug: 'pdec',
    resume: 'Projet phare de développement économique et local en Casamance (Ziguinchor, Sédhiou, Kolda).',
    description: "Le PDEC intervient dans les régions de Ziguinchor, Sédhiou et Kolda (60 communes) pour renforcer la gouvernance locale inclusive, la connectivité, les infrastructures résilientes au climat, l'inclusion sociale et la cohésion communautaire. L'ARD de Ziguinchor est agence partenaire de mise en œuvre : élaboration et actualisation des PDC et suivi des sous-projets communautaires. Financement : Banque mondiale (IDA).",
    organismePilote: 'PDEC / Banque Mondiale',
    statut: 'actif',
    budgetTotal: 45000000000,
    dateDebut: '2022-01-01',
    dateFin: '2027-12-31',
  },
  {
    id: 'prog-paijef',
    nom: "Projet d'Appui à l'Insertion Professionnelle des Jeunes et des Femmes formés",
    acronyme: 'PAIJEF',
    slug: 'paijef',
    resume: 'Insertion professionnelle des jeunes diplômés et des femmes de la région de Ziguinchor.',
    description: "Le PAIJEF vise l'insertion professionnelle des jeunes diplômés et des femmes. L'ARD de Ziguinchor pilote des missions de suivi des stagiaires, des actions auprès des entreprises, et le Dispositif Territorial de Premier Emploi, avec une démarche d'inclusion des personnes en situation de handicap.",
    organismePilote: 'ARD Ziguinchor / Coopération',
    statut: 'actif',
    budgetTotal: 1200000000,
    dateDebut: '2023-01-01',
    dateFin: '2026-12-31',
  },
  {
    id: 'prog-pacasen',
    nom: 'Programme d’Appui aux Communes et agglomérations du Sénégal',
    acronyme: 'PACASEN',
    slug: 'pacasen',
    resume: "Programme d'appui aux infrastructures et à la gestion des communes et agglomérations.",
    description: "Le PACASEN finance des infrastructures de base et renforce les capacités de gestion des communes et agglomérations. L'ARD de Ziguinchor contribue à son déploiement dans la région avec plus de 5 milliards FCFA mobilisés.",
    organismePilote: 'PACASEN / Banque Mondiale / AFD',
    statut: 'actif',
    budgetTotal: 5000000000,
    dateDebut: '2021-01-01',
    dateFin: '2026-12-31',
  },
  {
    id: 'prog-patip',
    nom: 'Projet d’Appui à la Territorialisation des politiques d’Insertion Professionnelle des Jeunes et des Femmes',
    acronyme: 'PATIP-JF',
    slug: 'patip-jf',
    resume: "Territorialisation des politiques d'insertion professionnelle des jeunes et des femmes.",
    description: "Le PATIP-JF déploie des politiques d'insertion professionnelle à l'échelle territoriale à travers 18 communes de la région de Ziguinchor. L'ARD en coordonne localement la mise en œuvre.",
    organismePilote: 'ARD Ziguinchor / Ministère du Travail',
    statut: 'actif',
    budgetTotal: 850000000,
    dateDebut: '2024-01-01',
    dateFin: '2026-12-31',
  },
  {
    id: 'prog-gcl',
    nom: 'Programme pour la gouvernance concertée du littoral',
    acronyme: 'GCL',
    slug: 'gouvernance-littoral',
    resume: "Gouvernance concertée des ressources naturelles littorales (avec l'AFD).",
    description: "Programme porté avec l'AFD sur la gouvernance des ressources naturelles, la protection de la mangrove, les territoires côtiers et la résilience face à l'érosion marine en Casamance.",
    organismePilote: 'AFD / ARD Ziguinchor',
    statut: 'actif',
    budgetTotal: 2500000000,
    dateDebut: '2023-06-01',
    dateFin: '2027-06-30',
  },
  {
    id: 'prog-bioclimate',
    nom: 'BIOCLIMATE Finance',
    acronyme: 'BIOCLIMATE',
    slug: 'bioclimate-finance',
    resume: 'Restauration de la biodiversité et technologies bas carbone (Ziguinchor, Kafountine).',
    description: "Programme d'appui à la résilience des écosystèmes et des communautés par la restauration de la biodiversité et le déploiement de technologies bas carbone, avec ENDA ENERGIE, les ARD et les collectivités locales.",
    organismePilote: 'ENDA ENERGIE',
    statut: 'actif',
    budgetTotal: 1800000000,
    dateDebut: '2023-01-01',
    dateFin: '2027-12-31',
  },
];

export const mockProjets = [
  {
    id: 'proj-vallee-mpack',
    titre: 'Aménagement de la vallée de Mpack',
    slug: 'amenagement-vallee-mpack',
    resume: "Aménagement hydro-agricole de la vallée de Mpack (Ziguinchor, PDEC).",
    description: "Travaux d'aménagement de la vallée de Mpack dans le cadre du PDEC, visant à valoriser les bas-fonds, améliorer la production agricole et renforcer la sécurité alimentaire. Le PDEC prévoit la réhabilitation de 23 vallées rizicoles couvrant 3 300 hectares en Casamance.",
    objectifs: "Valoriser les bas-fonds ; améliorer la production rizicole ; renforcer la sécurité alimentaire.",
    secteur: mockSecteurs[0],
    secteurId: 'sec-agri',
    programme: mockProgrammes[0],
    programmeId: 'prog-pdec',
    statut: 'encours',
    niveauAvancement: 45,
    budget: 300000000,
    beneficiaires: 15000,
    departement: mockDepartements[0],
    commune: mockCommunes[0],
    dateDebut: '2024-03-01',
    dateFinPrevue: '2026-11-30',
  },
  {
    id: 'proj-vallees-rizicoles',
    titre: 'Réhabilitation de 23 vallées rizicoles',
    slug: 'rehabilitation-vallees-rizicoles',
    resume: "Réhabilitation de 23 vallées rizicoles (dont 11 dans la région de Ziguinchor) sur 3 300 ha.",
    description: "Le PDEC suit la réhabilitation de 23 vallées rizicoles pour renforcer la souveraineté alimentaire en Basse-Casamance. Les travaux incluent des diguettes anti-sel, des canaux de rétention d'eau douce et l'octroi d'intrants certifiés.",
    objectifs: "Augmenter les superficies emblavées ; améliorer les rendements ; sécuriser les productions contre la salinisation des terres.",
    secteur: mockSecteurs[0],
    secteurId: 'sec-agri',
    programme: mockProgrammes[0],
    programmeId: 'prog-pdec',
    statut: 'encours',
    niveauAvancement: 55,
    budget: 500000000,
    beneficiaires: 20000,
    departement: mockDepartements[1],
    commune: mockCommunes[6],
    dateDebut: '2023-06-01',
    dateFinPrevue: '2026-12-31',
  },
  {
    id: 'proj-pistes-rurales',
    titre: 'Pistes rurales de désenclavement',
    slug: 'pistes-rurales-desenclavement',
    resume: "Construction et réhabilitation de 131 km de pistes rurales de production.",
    description: "Le programme PDEC finance la réalisation de pistes rurales pour désenclaver les bassins de production de la Basse-Casamance (notamment l'axe Mpack–Soukouta et les pistes du Blouf) et faciliter l'évacuation des produits agricoles vers les marchés urbains.",
    objectifs: "Désenclaver les terroirs ruraux ; faciliter l'accès aux marchés ; réduire les coûts de transport.",
    secteur: mockSecteurs[1],
    secteurId: 'sec-infra',
    programme: mockProgrammes[0],
    programmeId: 'prog-pdec',
    statut: 'encours',
    niveauAvancement: 60,
    budget: 450000000,
    beneficiaires: 25000,
    departement: mockDepartements[0],
    commune: mockCommunes[4],
    dateDebut: '2023-09-01',
    dateFinPrevue: '2026-08-31',
  },
  {
    id: 'proj-infras-sociales',
    titre: 'Infrastructures sociales de base à Ziguinchor',
    slug: 'infrastructures-sociales-ziguinchor',
    resume: "Construction de sous-projets d'écoles, cases de santé et forages dans 14 communes.",
    description: "Dans le cadre du PDEC, livraison et réception de sous-projets de construction d'équipements sociaux de base (écoles élémentaires, postes de santé, périmètres maraîchers solaires) dans plusieurs communes cibles de la région.",
    objectifs: "Renforcer l'accès aux services sociaux de base ; réduire les disparités territoriales ; améliorer les conditions de vie.",
    secteur: mockSecteurs[2],
    secteurId: 'sec-edu',
    programme: mockProgrammes[0],
    programmeId: 'prog-pdec',
    statut: 'encours',
    niveauAvancement: 75,
    budget: 400000000,
    beneficiaires: 30000,
    departement: mockDepartements[2],
    commune: mockCommunes[11],
    dateDebut: '2023-01-15',
    dateFinPrevue: '2026-06-30',
  },
  {
    id: 'proj-gare-routiere',
    titre: 'Construction de la nouvelle gare routière de Ziguinchor',
    slug: 'gare-routiere-ziguinchor',
    resume: "Investissement structurant PACASEN : construction du pôle d'échange multimodal de Ziguinchor.",
    description: "Investissement structurant financé dans le cadre du PACASEN. L'ARD a accompagné la Commune de Ziguinchor dans la maîtrise d'ouvrage déléguée, les études d'impact et la concertation avec les transporteurs.",
    objectifs: "Moderniser la mobilité urbaine et interurbaine ; désengorger le centre-ville ; sécuriser le transit des voyageurs.",
    secteur: mockSecteurs[1],
    secteurId: 'sec-infra',
    programme: mockProgrammes[2],
    programmeId: 'prog-pacasen',
    statut: 'planifie',
    niveauAvancement: 25,
    budget: 600000000,
    beneficiaires: 50000,
    departement: mockDepartements[0],
    commune: mockCommunes[0],
    dateDebut: '2024-06-01',
    dateFinPrevue: '2027-03-31',
  },
];

export const mockActualites = [
  {
    id: 'actu-1',
    titre: "Atelier de renforcement des capacités sur l'insertion professionnelle des personnes en situation de handicap",
    slug: 'insertion-professionnelle-handicap-atelier',
    resume: "Atelier de renforcement des capacités dans le cadre de l'Initiative FIT ! / PAIJEF à Ziguinchor.",
    contenu: "L'Agence Régionale de Développement (ARD) de Ziguinchor a réuni les acteurs institutionnels, les chefs d'entreprises et les associations partenaires pour un atelier de haut niveau axé sur l'inclusion professionnelle des personnes en situation de handicap. Animé avec les experts du programme PAIJEF, cet atelier a permis de définir des mécanismes d'accompagnement individualisé et d'adaptation des postes de travail.",
    categorie: mockCategoriesActualite[2],
    statut: 'publie',
    vue: 342,
    tempsLecture: 4,
    tags: ['PAIJEF', 'Handicap', 'Insertion', 'Ziguinchor'],
    datePublication: '2026-02-21T10:00:00Z',
    createdAt: '2026-02-21T10:00:00Z',
    updatedAt: '2026-02-21T10:00:00Z',
    imagePrincipale: '/img_banniere.jpg',
    auteur: { nom: 'ARD', prenom: 'Communication' },
  },
  {
    id: 'actu-2',
    titre: 'Mission conjointe de suivi des stagiaires du PAIJEF – Phase 2',
    slug: 'suivi-stagiaires-paijef-phase2',
    resume: "Suivi des 113 stagiaires dans les entreprises d'accueil des départements de Ziguinchor, Bignona et Oussouye.",
    contenu: "Dans le cadre du PAIJEF, l'ARD de Ziguinchor a mené une tournée de terrain auprès de 45 entreprises partenaires afin d'évaluer l'intégration des stagiaires, leur montée en compétences et les perspectives d'embauche durable. Les retours des tuteurs d'entreprise témoignent d'une excellente dynamique.",
    categorie: mockCategoriesActualite[0],
    statut: 'publie',
    vue: 512,
    tempsLecture: 3,
    tags: ['PAIJEF', 'Stages', 'Jeunesse', 'Emploi'],
    datePublication: '2026-02-14T09:30:00Z',
    createdAt: '2026-02-14T09:30:00Z',
    updatedAt: '2026-02-14T09:30:00Z',
    imagePrincipale: '/img_banniere.jpg',
    auteur: { nom: 'Direction', prenom: 'ARD' },
  },
  {
    id: 'actu-3',
    titre: 'Publication de la liste des candidats présélectionnés PATIP-JF',
    slug: 'preselection-candidats-patip-jf',
    resume: "Publication de la liste officielle des candidats présélectionnés dans les 18 communes cibles de la région.",
    contenu: "Le comité de sélection du Projet d'Appui à la Territorialisation des politiques d'Insertion Professionnelle des Jeunes et des Femmes (PATIP-JF), réuni au siège de l'ARD de Ziguinchor, rend publique la liste des bénéficiaires retenus pour les formations qualifiantes et les stages d'immersion communaux.",
    categorie: mockCategoriesActualite[1],
    statut: 'publie',
    vue: 890,
    tempsLecture: 2,
    tags: ['PATIP-JF', 'Présélection', 'Jeunes', 'Femmes'],
    datePublication: '2026-01-28T14:00:00Z',
    createdAt: '2026-01-28T14:00:00Z',
    updatedAt: '2026-01-28T14:00:00Z',
    imagePrincipale: '/img_banniere.jpg',
    auteur: { nom: 'Guichet', prenom: 'Emploi' },
  },
  {
    id: 'actu-4',
    titre: 'Lancement des travaux de désenclavement et de réhabilitation des vallées rizicoles',
    slug: 'lancement-travaux-vallees-rizicoles',
    resume: "Démarrage effectif des chantiers hydro-agricoles dans les communes de Mpack, Boutoupa et Coubalan.",
    contenu: "Le Gouverneur de la région de Ziguinchor, accompagné du Directeur de l'ARD et des représentants de la Banque Mondiale, a procédé au lancement officiel des travaux d'aménagement de 3 300 hectares de vallées rizicoles au titre du PDEC. Ces aménagements permettront de protéger les rizières contre l'intrusion saline et d'assurer deux cycles de récolte par an.",
    categorie: mockCategoriesActualite[0],
    statut: 'publie',
    vue: 420,
    tempsLecture: 5,
    tags: ['Agriculture', 'PDEC', 'Riziculture', 'Casamance'],
    datePublication: '2026-01-15T11:00:00Z',
    createdAt: '2026-01-15T11:00:00Z',
    updatedAt: '2026-01-15T11:00:00Z',
    imagePrincipale: '/img_banniere.jpg',
    auteur: { nom: 'ARD', prenom: 'Communication' },
  },
];

export const mockOpportunites = [
  {
    id: 'opp-1',
    titre: "Appel à candidatures pour la sélection de jeunes diplômés stagiaires (PAIJEF)",
    slug: 'appel-candidatures-paijef-2024',
    resume: "Sélection de jeunes diplômés stagiaires au profit du secteur privé de la région de Ziguinchor.",
    description: "Dans le cadre du Projet d'Appui à l'Insertion des Jeunes et des Femmes Formés (PAIJEF), l'ARD de Ziguinchor lance un appel à candidatures pour 50 nouveaux stages rémunérés au sein d'entreprises locales et de coopératives agricoles régionales.",
    type: mockTypesOpportunite[3],
    organisme: 'ARD Ziguinchor / PAIJEF',
    secteur: 'Insertion professionnelle',
    statut: 'ouvert',
    dateDebut: '2026-02-01',
    dateLimite: '2026-04-30',
    conditions: "Être titulaire d'un diplôme de l'enseignement supérieur ou technique (Bac+2 minimum), résider dans la région de Ziguinchor, être âgé de 18 à 35 ans (jusqu'à 40 ans pour les candidats en situation de handicap).",
  },
  {
    id: 'opp-2',
    titre: "Appel concernant 113 stages professionnels (PAIJEF – PATIP-JF)",
    slug: 'appel-113-stages-paijef-patip-jf',
    resume: "Offre de stages professionnels indemnisés (80 000 à 110 000 FCFA/mois) sur 9 mois.",
    description: "L'ARD de Ziguinchor publie un appel concernant 113 stages professionnels dans les collectivités territoriales, structures de santé et PME régionales pour l'année 2026.",
    type: mockTypesOpportunite[3],
    organisme: 'ARD Ziguinchor / PAIJEF / PATIP-JF',
    secteur: 'Insertion professionnelle',
    statut: 'ouvert',
    dateDebut: '2026-01-15',
    dateLimite: '2026-05-15',
    conditions: "Être un jeune diplômé ou qualifié de la région. Durée du stage : 9 mois avec accompagnement post-stage.",
  },
  {
    id: 'opp-3',
    titre: "Avis d'appel d'offres : Travaux d'aménagement hydro-agricole de vallées",
    slug: 'appel-offres-amenagement-vallees',
    resume: "Travaux de terrassement, diguettes et ouvrages régulateurs d'eau dans le département de Bignona.",
    description: "L'ARD de Ziguinchor, pour le compte du projet PDEC, invite les entreprises qualifiées de travaux publics et d'hydraulique à soumettre leurs offres pour la réhabilitation des bas-fonds rizicoles.",
    type: mockTypesOpportunite[0],
    organisme: 'ARD Ziguinchor / PDEC',
    secteur: 'Génie civil & Hydraulique',
    statut: 'ouvert',
    dateDebut: '2026-02-10',
    dateLimite: '2026-04-10',
    conditions: "Entreprises BTP enregistrées au Sénégal, disposant des garanties bancaires et du matériel technique requis dans le dossier d'appel d'offres (DAO).",
  },
];

export const mockPartenaires = [
  {
    id: 'part-bm',
    nom: 'Banque Mondiale',
    sigle: 'BM',
    slug: 'banque-mondiale',
    type: mockTypesPartenaires[0],
    pays: 'International / Sénégal',
    ville: 'Dakar',
    siteWeb: 'https://www.banquemondiale.org/fr/country/senegal',
    description: "La Banque Mondiale accompagne l'ARD de Ziguinchor à travers le financement du PDEC et du PACASEN pour les infrastructures territoriales et le développement économique.",
    statut: 'actif',
    logo: '/logo_ardz.png',
  },
  {
    id: 'part-giz',
    nom: 'GIZ Sénégal',
    sigle: 'GIZ',
    slug: 'giz-senegal',
    type: mockTypesPartenaires[0],
    pays: 'Allemagne / Sénégal',
    ville: 'Dakar',
    siteWeb: 'https://www.giz.de',
    description: "La coopération technique allemande soutient l'ARD sur le développement économique local, la formation professionnelle et la gestion durable des ressources naturelles.",
    statut: 'actif',
    logo: '/logo_ardz.png',
  },
  {
    id: 'part-usaid',
    nom: 'USAID Sénégal',
    sigle: 'USAID',
    slug: 'usaid-senegal',
    type: mockTypesPartenaires[0],
    pays: 'États-Unis / Sénégal',
    ville: 'Dakar',
    siteWeb: 'https://www.usaid.gov/senegal',
    description: "Soutien aux filières agricoles durables, à la gouvernance locale et à la résilience climatique en Casamance.",
    statut: 'actif',
    logo: '/logo_ardz.png',
  },
  {
    id: 'part-bretagne',
    nom: 'Région Bretagne',
    sigle: 'Bretagne',
    slug: 'region-bretagne',
    type: mockTypesPartenaires[2],
    pays: 'France',
    ville: 'Rennes',
    siteWeb: 'https://www.bretagne.bzh',
    description: "Partenaire historique de coopération décentralisée dans les domaines du développement territorial, de la formation et des échanges interculturels.",
    statut: 'actif',
    logo: '/logo_ardz.png',
  },
  {
    id: 'part-ansd',
    nom: 'Agence Nationale de la Statistique et de la Démographie',
    sigle: 'ANSD',
    slug: 'ansd',
    type: mockTypesPartenaires[2],
    pays: 'Sénégal',
    ville: 'Dakar',
    siteWeb: 'https://www.ansd.sn',
    description: "Fourniture de données statistiques officielles et appui méthodologique pour l'Observatoire Territorial de l'ARD.",
    statut: 'actif',
    logo: '/logo_ardz.png',
  },
];

export const mockEvenements = [
  {
    id: 'evt-1',
    titre: "Session ordinaire du Conseil d'Administration de l'ARD",
    slug: 'session-conseil-administration-2026',
    description: "Examen du bilan des activités 2025, validation du plan de travail et du budget annuel 2026 en présence des élus régionaux et partenaires.",
    dateDebut: '2026-04-15T09:00:00Z',
    dateFin: '2026-04-15T17:00:00Z',
    lieu: 'Siège de l\'ARD, Ziguinchor',
    statut: 'a_venir',
    organisateur: 'Direction Générale ARD',
  },
  {
    id: 'evt-2',
    titre: "Atelier de restitution de l'Observatoire Territorial de la Basse-Casamance",
    slug: 'restitution-observatoire-territorial',
    description: "Présentation des indicateurs socio-économiques récents par département et commune aux décideurs locaux et ONG partenaires.",
    dateDebut: '2026-04-28T09:30:00Z',
    dateFin: '2026-04-28T15:00:00Z',
    lieu: 'Hôtel Néma Kadior, Ziguinchor',
    statut: 'a_venir',
    organisateur: 'Cellule Observatoire ARD',
  },
];

export const mockDocuments = [
  {
    id: 'doc-prdi',
    titre: 'Plan Régional de Développement Intégré (PRDI) de Ziguinchor 2024-2028',
    slug: 'prdi-ziguinchor-2024-2028',
    description: 'Document stratégique fixant les grandes orientations et investissements prioritaires de la région pour les cinq années.',
    categorie: mockCategoriesDocument[2],
    categorieId: 'cat-pla',
    annee: 2024,
    tailleFichier: '4.8 Mo',
    format: 'PDF',
    url: '#',
    estTerritoriale: true,
  },
  {
    id: 'doc-rapport-2025',
    titre: "Rapport Annuel d'Activités ARD Ziguinchor 2025",
    slug: 'rapport-activites-ard-2025',
    description: "Bilan complet des réalisations, projets accompagnés et gestion budgétaire de l'exercice 2025.",
    categorie: mockCategoriesDocument[0],
    categorieId: 'cat-rap',
    annee: 2025,
    tailleFichier: '3.2 Mo',
    format: 'PDF',
    url: '#',
    estTerritoriale: false,
  },
  {
    id: 'doc-guide-pdc',
    titre: "Guide méthodologique d'élaboration des Plans de Développement Communaux (PDC)",
    slug: 'guide-methodologique-pdc',
    description: "Outil d'accompagnement des maires et équipes municipales pour la planification territoriale participative.",
    categorie: mockCategoriesDocument[3],
    categorieId: 'cat-gui',
    annee: 2024,
    tailleFichier: '2.1 Mo',
    format: 'PDF',
    url: '#',
    estTerritoriale: true,
  },
  {
    id: 'doc-etude-riz',
    titre: "Diagnostic de la filière rizicole et de l'impact des vallées aménagées en Basse-Casamance",
    slug: 'diagnostic-filiere-riz-casamance',
    description: "Étude d'impact agronomique et socio-économique réalisée avec l'ANSD et le PDEC.",
    categorie: mockCategoriesDocument[1],
    categorieId: 'cat-etu',
    annee: 2025,
    tailleFichier: '5.5 Mo',
    format: 'PDF',
    url: '#',
    estTerritoriale: true,
  },
];

export const mockFaqs = [
  {
    id: 'faq-1',
    question: "Qu'est-ce que l'ARD Ziguinchor ?",
    reponse: "L'Agence Régionale de Développement (ARD) de Ziguinchor est un établissement public chargé de promouvoir et de coordonner le développement économique, social et culturel de la région de Ziguinchor. Elle accompagne les collectivités locales, les porteurs de projets et les partenaires au développement.",
    categorieId: 'cat-gen',
    ordre: 1,
  },
  {
    id: 'faq-2',
    question: "Quelles sont les missions principales de l'ARD ?",
    reponse: "L'ARD Ziguinchor a pour missions : l'élaboration et le suivi du plan régional de développement intégré (PRDI), l'appui technique aux collectivités locales, la promotion des investissements et de l'entrepreneuriat local, la mise en œuvre de programmes sectoriels et la valorisation des potentialités régionales.",
    categorieId: 'cat-gen',
    ordre: 2,
  },
  {
    id: 'faq-3',
    question: "Quels sont les départements couverts par l'ARD Ziguinchor ?",
    reponse: "L'ARD Ziguinchor couvre l'intégralité des 3 départements de la région : Ziguinchor, Bignona et Oussouye, ainsi que leurs 30 communes.",
    categorieId: 'cat-gen',
    ordre: 3,
  },
  {
    id: 'faq-4',
    question: "Comment l'ARD soutient-elle les porteurs de projets ?",
    reponse: "L'ARD accompagne les porteurs de projets à travers l'orientation technique, la mise en réseau avec les partenaires financiers, l'appui au montage de dossiers et le suivi-évaluation. Les opportunités ouvertes sont publiées dans la section Opportunités du site.",
    categorieId: 'cat-proj',
    ordre: 4,
  },
  {
    id: 'faq-5',
    question: "Comment candidater à une opportunité publiée par l'ARD ?",
    reponse: "Rendez-vous dans la section « Opportunités » du site, consultez les conditions d'éligibilité et suivez les instructions de dépôt de candidature mentionnées sur la fiche correspondante.",
    categorieId: 'cat-proj',
    ordre: 5,
  },
  {
    id: 'faq-6',
    question: "L'observatoire territorial est-il accessible au public ?",
    reponse: "Oui, la rubrique « Observatoire » permet de consulter librement les indicateurs socio-économiques de la région par secteur, département et commune.",
    categorieId: 'cat-doc',
    ordre: 6,
  },
];

export const mockMembres = [
  { id: 'm-1', nom: 'Goudiaby', prenom: 'Mamadou', poste: 'Directeur Général', email: 'direction@ard-ziguinchor.sn', telephone: '+221 33 991 12 34', ordre: 1, actif: true },
  { id: 'm-2', nom: 'Diédhiou', prenom: 'Fatou', poste: 'Responsable Planification & Aménagement', email: 'planification@ard-ziguinchor.sn', telephone: '+221 33 991 12 35', ordre: 2, actif: true },
  { id: 'm-3', nom: 'Sané', prenom: 'Abdoulaye', poste: 'Responsable Suivi-Évaluation & Observatoire', email: 'observatoire@ard-ziguinchor.sn', telephone: '+221 33 991 12 36', ordre: 3, actif: true },
  { id: 'm-4', nom: 'Badji', prenom: 'Aminata', poste: 'Coordonnatrice Insertion & Genre (PAIJEF/PATIP-JF)', email: 'insertion@ard-ziguinchor.sn', telephone: '+221 33 991 12 37', ordre: 4, actif: true },
];

export const mockIndicateurs = [
  { id: 'ind-1', libelle: "Taux d'accès à l'eau potable", valeur: '74.5', unite: '%', annee: 2025, secteurId: 'sec-infra', departementId: 'dept-zg' },
  { id: 'ind-2', libelle: "Superficie de vallées réhabilitées", valeur: '3300', unite: 'ha', annee: 2025, secteurId: 'sec-agri', departementId: 'dept-bn' },
  { id: 'ind-3', libelle: "Taux brut de scolarisation primaire", valeur: '88.2', unite: '%', annee: 2025, secteurId: 'sec-edu', departementId: 'dept-oy' },
  { id: 'ind-4', libelle: "Linéaire de pistes rurales aménagées", valeur: '131', unite: 'km', annee: 2025, secteurId: 'sec-infra', departementId: 'dept-zg' },
];

export const mockGalerie = [
  {
    id: 'gal-1',
    titre: 'Aménagement hydro-agricole de Mpack',
    description: 'Chantiers de terrassement et réhabilitation des diguettes anti-sel dans la vallée de Mpack.',
    date: '2026-02-15',
    images: [{ id: 'img-1', url: '/img_banniere.jpg', legende: 'Vue panoramique des travaux de la vallée' }],
  },
  {
    id: 'gal-2',
    titre: 'Atelier inclusion et formation PAIJEF',
    description: 'Séance pratique de formation professionnelle des jeunes à Ziguinchor.',
    date: '2026-02-10',
    images: [{ id: 'img-2', url: '/img_banniere.jpg', legende: 'Remise des attestations de stage' }],
  },
];
